# this is optional
max_fps = 30
fullscreen = false

[audio]
buffer_size = 256
num_buffers = 16
fft_size = 1024
cutoff = 0.01
q = 0.5
gain = 1.0

[uniforms]
decay = 0.3
thickness = 10.0
min_thickness = 1.5
thinning = 0.05
base_hue = 0.0
desaturation = 0.1
colorize = true

[debug]
# when buffers are dropped, print "!"
print_drop = true
